"""Add percent complete and constraints

Revision ID: dfe853135047
Revises: 9c1307387a70
Create Date: 2026-09-02 10:32:16.140890
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'dfe853135047'
down_revision: str | None = '9c1307387a70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actual_progress', sa.Column('percent_complete', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actual_progress', 'percent_complete')
    # ### end Alembic commands ###
