"""index foreign keys to users (phase 11)

Six foreign keys to ``users`` had no index. None of them is used as a query
filter -- they are audit columns, written once and read back with the row --
so this is not about read performance.

It is about deletes. Every one of these is ``ON DELETE SET NULL``, and to
enforce that PostgreSQL must find the referencing rows when a user is removed.
Without an index that means a sequential scan of each child table, and
``actual_progress`` is the largest table in the schema and the fastest growing.

Measured on a seeded 5,000-activity project with 91,470 progress rows, deleting
one user (median of three runs):

    without these indexes:   12.6 ms
    with these indexes:       5.5 ms

A small absolute saving today, deliberately recorded as such rather than
oversold. What makes it worth doing is the shape: the unindexed cost scales
with table size, so the same delete against a few million progress rows is a
multi-second table scan per child table, while the indexed cost stays flat.

Revision ID: 82904d0d199d
Revises: 6c4ed7f85001
Create Date: 2026-09-04 10:32:32.439003
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '82904d0d199d'
down_revision: str | None = '6c4ed7f85001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_matches_reviewed_by_id'), 'activity_matches', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_actual_progress_reported_by_id'), 'actual_progress', ['reported_by_id'], unique=False)
    op.create_index(op.f('ix_delay_model_versions_trained_by_id'), 'delay_model_versions', ['trained_by_id'], unique=False)
    op.create_index(op.f('ix_delay_predictions_generated_by_id'), 'delay_predictions', ['generated_by_id'], unique=False)
    op.create_index(op.f('ix_schedules_uploaded_by_id'), 'schedules', ['uploaded_by_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_uploaded_by_id'), 'uploaded_files', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_uploaded_by_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_schedules_uploaded_by_id'), table_name='schedules')
    op.drop_index(op.f('ix_delay_predictions_generated_by_id'), table_name='delay_predictions')
    op.drop_index(op.f('ix_delay_model_versions_trained_by_id'), table_name='delay_model_versions')
    op.drop_index(op.f('ix_actual_progress_reported_by_id'), table_name='actual_progress')
    op.drop_index(op.f('ix_activity_matches_reviewed_by_id'), table_name='activity_matches')
    # ### end Alembic commands ###
