"""Add progress model

Revision ID: 9c1307387a70
Revises: b839d30e73b7
Create Date: 2026-09-02 10:14:46.963353
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9c1307387a70'
down_revision: str | None = 'b839d30e73b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_progress',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('actual_quantity', sa.Float(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_actual_progress_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], name=op.f('fk_actual_progress_reported_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actual_progress')),
    sa.UniqueConstraint('activity_id', 'reporting_date', name='uq_progress_activity_date')
    )
    op.create_index(op.f('ix_actual_progress_activity_id'), 'actual_progress', ['activity_id'], unique=False)
    op.create_index(op.f('ix_actual_progress_reporting_date'), 'actual_progress', ['reporting_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actual_progress_reporting_date'), table_name='actual_progress')
    op.drop_index(op.f('ix_actual_progress_activity_id'), table_name='actual_progress')
    op.drop_table('actual_progress')
    # ### end Alembic commands ###
