"""Add source_report_id to progress

Revision ID: 31186611e9b5
Revises: dfe853135047
Create Date: 2026-09-02 10:37:21.942650
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '31186611e9b5'
down_revision: str | None = 'dfe853135047'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actual_progress', sa.Column('source_report_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_actual_progress_source_report_id'), 'actual_progress', ['source_report_id'], unique=False)
    op.create_foreign_key(op.f('fk_actual_progress_source_report_id_progress_reports'), 'actual_progress', 'progress_reports', ['source_report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_actual_progress_source_report_id_progress_reports'), 'actual_progress', type_='foreignkey')
    op.drop_index(op.f('ix_actual_progress_source_report_id'), table_name='actual_progress')
    op.drop_column('actual_progress', 'source_report_id')
    # ### end Alembic commands ###
