"""Add new columns for Meta integration

Revision ID: 5b67e650f985
Revises: 6c4ed7f85001
Create Date: 2026-09-04 13:47:35.665168
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5b67e650f985'
down_revision: str | None = '6c4ed7f85001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('provider_message_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_uploaded_files_provider_message_id'), 'uploaded_files', ['provider_message_id'], unique=True)
    op.add_column('users', sa.Column('phone_normalised', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_phone_normalised'), 'users', ['phone_normalised'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_normalised'), table_name='users')
    op.drop_column('users', 'phone_normalised')
    op.drop_index(op.f('ix_uploaded_files_provider_message_id'), table_name='uploaded_files')
    op.drop_column('uploaded_files', 'provider_message_id')
    # ### end Alembic commands ###
