"""Add schedule models

Revision ID: d93681770df1
Revises: e7bd0ac32b44
Create Date: 2026-09-01 13:36:17.443322
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd93681770df1'
down_revision: str | None = 'e7bd0ac32b44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_schedules_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_schedules_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_is_deleted'), 'schedules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_table('activities',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('activity_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('wbs_path', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=50), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_finish', sa.Date(), nullable=True),
    sa.Column('budgeted_quantity', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], name=op.f('fk_activities_parent_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_activities_schedule_id_schedules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_activity_code'), 'activities', ['activity_code'], unique=False)
    op.create_index(op.f('ix_activities_parent_id'), 'activities', ['parent_id'], unique=False)
    op.create_index(op.f('ix_activities_schedule_id'), 'activities', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_activities_wbs_path'), 'activities', ['wbs_path'], unique=False)
    op.create_table('activity_dependencies',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('predecessor_id', sa.UUID(), nullable=False),
    sa.Column('successor_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=20), nullable=False),
    sa.Column('lag', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], name=op.f('fk_activity_dependencies_predecessor_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_activity_dependencies_schedule_id_schedules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['activities.id'], name=op.f('fk_activity_dependencies_successor_id_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_dependencies'))
    )
    op.create_index(op.f('ix_activity_dependencies_predecessor_id'), 'activity_dependencies', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_schedule_id'), 'activity_dependencies', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_activity_dependencies_successor_id'), 'activity_dependencies', ['successor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_dependencies_successor_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_schedule_id'), table_name='activity_dependencies')
    op.drop_index(op.f('ix_activity_dependencies_predecessor_id'), table_name='activity_dependencies')
    op.drop_table('activity_dependencies')
    op.drop_index(op.f('ix_activities_wbs_path'), table_name='activities')
    op.drop_index(op.f('ix_activities_schedule_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_parent_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_code'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_is_deleted'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
